# -*- coding: utf-8 -*-
"""Utility library for generating CHI660E macro scripts."""
import os
import sys
import datetime as dt

class CHI660e:
    """Wrapper for CHI660E macro commands."""

    def __init__(self):
        self.path = os.getcwd()
        self.fileoverride = True
        self.dummyon = False

    def beep(self, file, times: int, interval: float):
        print(f"for:{times}", file=file)
        print("  beep", file=file)
        print(f"  delay:{interval}", file=file)
        print("next", file=file)

    def init_output_txt(self, file):
        print("# Welcome to Macro Command!", file=file)
        print("# This script is generated by CHI660_Macro", file=file)
        print("folder:" + self.path, file=file)
        print(" ", file=file)

    def gene_mcr_file(self, file):
        file.seek(0, 0)
        with open('output.mcr', 'w') as mcr_file:
            mcr_file.write('Hh\x00\x00' + file.read())
        file.seek(0, 2)

    # --- Linear sweep voltammetry ---
    def init_lsv_tech(self, ei=0.0, ef=-0.1, v=0.01, si=0.001, qt=2.0, sens=1e-3):
        self.lsv_ei = ei
        self.lsv_ef = ef
        self.lsv_v = v
        self.lsv_si = si
        self.lsv_qt = qt
        self.lsv_sens = sens

    def run_lsv(self, file, filename='untitled', tsave=True, autosens=True, add_note=False):
        if add_note:
            print(f"# LSV from {self.lsv_ei}V to {self.lsv_ef}V with {self.lsv_v*1000}mV/s", file=file)
        print("tech:lsv", file=file)
        print(f"ei:{self.lsv_ei}", file=file)
        print(f"ef:{self.lsv_ef}", file=file)
        print(f"v:{self.lsv_v}", file=file)
        print(f"si:{self.lsv_si}", file=file)
        print(f"qt:{self.lsv_qt}", file=file)
        print(f"sens:{self.lsv_sens}", file=file)
        if autosens:
            print("autosens", file=file)
        print("run", file=file)
        print(f"save:{filename}", file=file)
        if tsave:
            print(f"tsave:{filename}", file=file)
        print(" ", file=file)

    # --- Cyclic voltammetry ---
    def init_cv_tech(self, ei=0.0, eh=-0.1, el=-0.1, pn="p", v=0.01, cl=32, si=0.001, qt=2.0, sens=1e-3):
        self.cv_ei = ei
        self.cv_eh = eh
        self.cv_el = el
        self.cv_pn = pn
        self.cv_v = v
        self.cv_cl = cl
        self.cv_si = si
        self.cv_qt = qt
        self.cv_sens = sens

    def run_cv(self, file, filename='untitled', tsave=True, autosens=True, add_note=False):
        if add_note:
            print(f"# CV from {self.cv_el}V to {self.cv_eh}V with {self.cv_v*1000}mV/s for {self.cv_cl} cycles", file=file)
        print("tech:cv", file=file)
        print(f"ei:{self.cv_ei}", file=file)
        print(f"eh:{self.cv_eh}", file=file)
        print(f"el:{self.cv_el}", file=file)
        print(f"cl:{self.cv_cl}", file=file)
        print(f"pn:{self.cv_pn}", file=file)
        print(f"v:{self.cv_v}", file=file)
        print(f"si:{self.cv_si}", file=file)
        print(f"qt:{self.cv_qt}", file=file)
        print(f"sens:{self.cv_sens}", file=file)
        if autosens:
            print("autosens", file=file)
        print("run", file=file)
        print(f"save:{filename}", file=file)
        if tsave:
            print(f"tsave:{filename}", file=file)
        print(" ", file=file)

    # --- Staircase CV ---
    def init_scv_tech(self, ei=0.0, ef=-0.1, incre=0.001, sw=0.001, prod=0.01, qt=2.0, sens=1e-3):
        self.scv_ei = ei
        self.scv_ef = ef
        self.scv_incre = incre
        self.scv_sw = sw
        self.scv_prod = prod
        self.scv_qt = qt
        self.scv_sens = sens

    def run_scv(self, file, filename='untitled', tsave=True, autosens=True, add_note=False):
        if add_note:
            print(f"# scv from {self.scv_ei}V to {self.scv_ef}V with {self.scv_incre*1000}V step for {self.scv_prod} period", file=file)
        print("tech:scv", file=file)
        print(f"ei:{self.scv_ei}", file=file)
        print(f"ef:{self.scv_ef}", file=file)
        print(f"incre:{self.scv_incre}", file=file)
        print(f"sw:{self.scv_sw}", file=file)
        print(f"prod:{self.scv_prod}", file=file)
        print(f"sens:{self.scv_sens}", file=file)
        print(f"qt:{self.scv_qt}", file=file)
        if autosens:
            print("autosens", file=file)
        print("run", file=file)
        print(f"save:{filename}", file=file)
        if tsave:
            print(f"tsave:{filename}", file=file)
        print(" ", file=file)

    # --- Chronoamperometry ---
    def init_it_tech(self, ei=0.0, si=0.1, st=600, qt=2.0, sens=1e-3):
        self.it_ei = ei
        self.it_si = si
        self.it_st = st
        self.it_qt = qt
        self.it_sens = sens

    def run_it(self, file, filename='untitled', tsave=True, autosens=True, add_note=False):
        if add_note:
            print(f"# it at {self.it_ei}V with {self.it_si}s inter for {self.it_st}s.", file=file)
        print("tech:it", file=file)
        print(f"ei:{self.it_ei}", file=file)
        print(f"si:{self.it_si}", file=file)
        print(f"st:{self.it_st}", file=file)
        print(f"qt:{self.it_qt}", file=file)
        print(f"sens:{self.it_sens}", file=file)
        if autosens:
            print("autosens", file=file)
        print("run", file=file)
        print(f"save:{filename}", file=file)
        if tsave:
            print(f"tsave:{filename}", file=file)
        print(" ", file=file)

    # --- Bulk electrolysis ---
    def init_be_tech(self, ei=0.0, iratio=0.5, si=0.1, bepe=-0.1, bept=2):
        self.be_ei = ei
        self.be_iratio = iratio
        self.be_si = si
        self.be_bepe = bepe
        self.be_bept = bept

    def run_be(self, file, filename='untitled', tsave=True, autosens=True, add_note=False):
        if add_note:
            print(f"# be at {self.be_ei}V with {self.be_si}s inter till {self.be_iratio}%.", file=file)
        print("tech:be", file=file)
        print(f"ei:{self.be_ei}", file=file)
        print(f"iratio:{self.be_iratio}", file=file)
        print(f"si:{self.be_si}", file=file)
        print(f"bepe:{self.be_bepe}", file=file)
        print(f"bept:{self.be_bept}", file=file)
        if autosens:
            print("autosens", file=file)
        print("run", file=file)
        print(f"save:{filename}", file=file)
        if tsave:
            print(f"tsave:{filename}", file=file)
        print(" ", file=file)

    # --- Impedance ---
    def init_imp_tech(self, ei=0.0, fl=1.0, fh=1e5, amp=0.005, qt=2.0, sens=1e-3):
        self.imp_ei = ei
        self.imp_fl = fl
        self.imp_fh = fh
        self.imp_amp = amp
        self.imp_qt = qt
        self.imp_sens = sens

    def run_imp(self, file, filename='untitled', tsave=True, autosens=True, add_note=False):
        if add_note:
            print(f"# imp at {self.imp_ei}V from {self.imp_fl}Hz to {self.imp_fh}Hz.", file=file)
        print("tech:imp", file=file)
        print(f"ei:{self.imp_ei}", file=file)
        print(f"fl:{self.imp_fl}", file=file)
        print(f"fh:{self.imp_fh}", file=file)
        print(f"amp:{self.imp_amp}", file=file)
        print(f"qt:{self.imp_qt}", file=file)
        print(f"sens:{self.imp_sens}", file=file)
        if autosens:
            print("autosens", file=file)
        print("run", file=file)
        print(f"save:{filename}", file=file)
        if tsave:
            print(f"tsave:{filename}", file=file)
        print(" ", file=file)
